### PR TITLE
Keycloak connector

### PR DESCRIPTION
**Pull request by Kerruba**
Update the avatar plugin to integrate the keycloak connector and updates the logic of how widgets are read from disk.
It maintains the compatibility with SecurityProblemSupport class provided by default with JHipster

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Kerruba** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Pull request merged**
